# Generated by Django 5.1.3 on 2024-11-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='parol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
