# Generated by Django 5.1.3 on 2024-11-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomer', '0005_alter_qiymat_qiymat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qiymat',
            old_name='qiymat',
            new_name='link',
        ),
        migrations.AddField(
            model_name='qiymat',
            name='nomer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
